/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * refreshmint backend
 * OpenAPI spec version: 0.1.0
 */
import type { RegisterCallResponseRetellLlmDynamicVariablesAnyOf } from './registerCallResponseRetellLlmDynamicVariablesAnyOf';

export type RegisterCallResponseRetellLlmDynamicVariables = RegisterCallResponseRetellLlmDynamicVariablesAnyOf | null;
